In [7]:
import cv2
import glob


# Read RGB image
females = [cv2.imread(file) for file in glob.glob('C:\\Users\\MeaadAlrshoud\\Documents\\GitHub\\Gender-Classification\\Female_Dataset\\*.jpg')]
males = [cv2.imread(file) for file in glob.glob('C:\\Users\\MeaadAlrshoud\\Documents\\GitHub\\Gender-Classification\\Male_Dataset\\*.jpg')]

#convert to greyscale
f_grey= [cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) for img in females]
m_grey=[cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) for img in males]
count=0
# print the images
'''for img in f_grey:
    # Output img with window name as 'image' 
    cv2.imshow('image',img)
    # Maintain output window utill 
    # user presses a key 
    cv2.waitKey(0)
    # Destroying present windows on screen 
    cv2.destroyAllWindows()
    '''



"for img in f_grey:\n    # Output img with window name as 'image' \n    cv2.imshow('image',img)\n    # Maintain output window utill \n    # user presses a key \n    cv2.waitKey(0)\n    # Destroying present windows on screen \n    cv2.destroyAllWindows()\n    "

#### Normalization

### Haar

### Haar

In [8]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
# Detect faces in the image
f_haar= [ face_cascade.detectMultiScale(
    img,
    scaleFactor=1.1,
    minNeighbors=5,
    minSize=(30, 30),
    flags = cv2.CASCADE_SCALE_IMAGE
) for img in f_grey]

m_haar=[face_cascade.detectMultiScale(
    img,
    scaleFactor=1.1,
    minNeighbors=5,
    minSize=(30, 30),
    flags = cv2.CASCADE_SCALE_IMAGE
) for img in m_grey]
m_haar

[array([[ 23,  83, 221, 221]], dtype=int32),
 array([[ 10,  85, 245, 245]], dtype=int32),
 array([[ 22,  87, 219, 219]], dtype=int32),
 array([[ 20,  83, 229, 229]], dtype=int32),
 array([[ 22,  84, 227, 227]], dtype=int32),
 array([[ 34,  99, 203, 203]], dtype=int32),
 array([[ 24,  87, 222, 222]], dtype=int32),
 array([[ 15,  80, 233, 233]], dtype=int32),
 array([[ 18,  84, 230, 230]], dtype=int32),
 array([[ 19,  86, 223, 223]], dtype=int32),
 array([[ 23,  95, 214, 214]], dtype=int32),
 array([[  9,  80, 239, 239]], dtype=int32),
 array([[ 22,  88, 217, 217]], dtype=int32),
 array([[ 27,  92, 216, 216]], dtype=int32),
 array([[ 25,  95, 214, 214]], dtype=int32),
 array([[ 28,  91, 210, 210]], dtype=int32),
 array([[ 21,  88, 220, 220]], dtype=int32),
 array([[ 26,  94, 210, 210]], dtype=int32),
 array([[ 26,  89, 216, 216]], dtype=int32),
 array([[ 21,  85, 223, 223]], dtype=int32),
 array([[ 25,  89, 222, 222]], dtype=int32),
 array([[ 33,  95, 203, 203]], dtype=int32),
 array([[ 

In [9]:
# print haar affect
print ("Found {0} faces!".format(len(f_haar)))


# Draw a rectangle around the faces
for (x, y, w, h) in f_haar:
    f_rec= [cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2) for img in females]
    m_rec=[cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2) for img in males]

        
cv2.imshow("Faces found", f_rec[0])
cv2.waitKey(0)

Found 99 faces!


ValueError: not enough values to unpack (expected 4, got 1)

### Face alignment

In [18]:
import face_alignment
from skimage import io
fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False)

#input = io.imread('../test/assets/aflw-test.jpg')
preds = fa.get_landmarks(m_haar)

ModuleNotFoundError: No module named 'face_alignment'

In [ ]:
# image using PIL module 
import sys, numpy as np, os 
# importing PIL 
from PIL import Image 
import glob
  
# Read image 
females2 = [Image.open(file) for file in glob.glob('C:\\Users\\MeaadAlrshoud\\Documents\\GitHub\\Gender-Classification\\Female_Dataset\\*.jpg')]
  

In [ ]:
print('X_data shape:', np.array(f_grey).shape)

[array([[ 27,  96, 211, 211]], dtype=int32), array([[ 28,  91, 212, 212]], dtype=int32), array([[ 31,  96, 206, 206]], dtype=int32), array([[ 22,  94, 220, 220]], dtype=int32), array([[ 27,  92, 216, 216]], dtype=int32), array([[ 25,  89, 219, 219]], dtype=int32), array([[ 27,  92, 220, 220]], dtype=int32), array([[ 28,  90, 211, 211]], dtype=int32), array([[ 37,  97, 200, 200]], dtype=int32), array([[ 27,  93, 212, 212]], dtype=int32), array([[ 28,  90, 213, 213]], dtype=int32), array([[ 23,  86, 224, 224]], dtype=int32), array([[ 22,  87, 220, 220]], dtype=int32), array([[ 21,  88, 219, 219]], dtype=int32), array([[ 25,  92, 217, 217]], dtype=int32), array([[ 24,  89, 216, 216]], dtype=int32), array([[ 24,  86, 220, 220]], dtype=int32), array([[ 30,  98, 204, 204]], dtype=int32), array([[ 28,  99, 210, 210]], dtype=int32), array([[ 28,  90, 211, 211]], dtype=int32), array([[ 28,  88, 214, 214]], dtype=int32), array([[ 29,  94, 209, 209]], dtype=int32), array([[ 31,  92, 204, 204]], d

In [ ]:

path=os.getcwd()
femaleP='C:/Users/meaad/Desktop/Gender/Female_Dataset/*.jpg'
X_data = []
files = glob.glob (femaleP)
for myFile in files:
    image = cv2.imread (myFile)
    if image is not None:
        X_data.append(image)
print('X_data shape:', np.array(X_data).shape)

In [ ]:
import cv2
import numpy as np
#Read Image
img = cv2.imread('C:\\Users\\MeaadAlrshoud\\Documents\\GitHub\\Gender-Classification\\Female_Dataset\\11a.jpg')
#Display Image
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#Applying Grayscale filter to image
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

im = np.float32(img) / 255.0

# Calculate gradient 
gx = cv2.Sobel(im, cv2.CV_32F, 1, 0, ksize=1)
gy = cv2.Sobel(im, cv2.CV_32F, 0, 1, ksize=1)

mag, angle = cv2.cartToPolar(gx, gy, angleInDegrees=True)

#Saving filtered image to new file
cv2.imwrite('test3.jpg',im)

In [ ]:
import matplotlib.pyplot as plt

from skimage.feature import hog
from skimage import data, exposure

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np


image =mpimg.imread('C:\\Users\\MeaadAlrshoud\\Documents\\GitHub\\Gender-Classification\\Female_Dataset\\11a.jpg')


fd, hog_image = hog(image, orientations=8, pixels_per_cell=(16, 16),
                    cells_per_block=(1, 1), visualize=True, multichannel=True)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(8, 4), sharex=True, sharey=True)

ax1.axis('off')
ax1.imshow(image, cmap=plt.cm.gray)
ax1.set_title('Input image')

# Rescale histogram for better display
hog_image_rescaled = exposure.rescale_intensity(hog_image, in_range=(0, 10))

ax2.axis('off')
ax2.imshow(hog_image_rescaled, cmap=plt.cm.gray)
ax2.set_title('Histogram of Oriented Gradients')
plt.show()

### HOG

In [ ]:
import matplotlib.pyplot as plt

from skimage.feature import hog
from skimage import data, exposure

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np

for img in f_grey:
    fd, hog_image = hog(img, orientations=8, pixels_per_cell=(16, 16),
                    cells_per_block=(1, 1), visualize=True, multichannel=True)
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(8, 4), sharex=True, sharey=True)

ax1.axis('off')
ax1.imshow(img, cmap=plt.cm.gray)
ax1.set_title('Input image')

# Rescale histogram for better display
hog_image_rescaled = exposure.rescale_intensity(hog_image, in_range=(0, 10))

ax2.axis('off')
ax2.imshow(hog_image_rescaled, cmap=plt.cm.gray)
ax2.set_title('Histogram of Oriented Gradients')